export enum ClassName {
    HINT_WRAP = 'newbie-hint-wrap',
    HINT_WRAP_VISIBLE = 'newbie-hint-wrap_visible',
    HINT_WRAP_CONTAINER = 'newbie-hint-wrap__container',
    HINT_WRAP_HINT = 'newbie-hint-wrap__hint',
    HINT_WRAP_ARROW = 'newbie-hint-wrap__arrow',
    HINT = 'newbie-hint',
    SHADOW = 'newbie-shadow',
    SHADOW_SVG = 'newbie-shadow__svg',
    SHADOW_VISIBLE = 'newbie-shadow_visible',
    SHADOW_OVERLAY = 'newbie-shadow__overlay',
    SHADOW_OVERLAY_TOP = 'newbie-shadow__overlay_top',
    SHADOW_OVERLAY_RIGHT = 'newbie-shadow__overlay_right',
    SHADOW_OVERLAY_BOTTOM = 'newbie-shadow__overlay_bottom',
    SHADOW_OVERLAY_LEFT = 'newbie-shadow__overlay_left',
    ARROW = 'newbie-arrow',
    ARROW_VISIBLE = 'newbie-arrow_visible',
}
